---
name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      -
        name: Install Brotli
        run: |
          sudo apt-get update
          sudo apt-get install libbrotli-dev
      -
        name: Run tests
        run: go test -race
      -
        name: Lint Go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
